# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import *




class Ui_about_wind(object):
    def setupUi(self, about_wind):
        about_wind.setObjectName("about_wind")
        about_wind.resize(421, 226)
        self.frame = QtWidgets.QFrame(about_wind)
        self.frame.setGeometry(QtCore.QRect(30, 30, 361, 171))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 10, 71, 20))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 301, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(110, 70, 131, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 100, 261, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(110, 130, 141, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(about_wind)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 111, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        
        self.retranslateUi(about_wind)
        QtCore.QMetaObject.connectSlotsByName(about_wind)

    def retranslateUi(self, about_wind):
        _translate = QtCore.QCoreApplication.translate
        about_wind.setWindowTitle(_translate("about_wind", "Form"))
        self.label.setText(_translate("about_wind", "Money Calc"))
        self.label_3.setText(_translate("about_wind", "Aplicacion pensada para el facil calculo de efectivo"))
        self.label_4.setText(_translate("about_wind", "Version: WinOS.0.1.0"))
        self.label_5.setText(_translate("about_wind", "This appRuns on any 64bit Windows System"))
        self.label_6.setText(_translate("about_wind", "Designed by: Astanine"))
        self.label_2.setText(_translate("about_wind", "Acerca De: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    about_wind = QtWidgets.QWidget()
    ui = Ui_about_wind()
    ui.setupUi(about_wind)
    about_wind.show()
    sys.exit(app.exec_())
